### PR TITLE
Improved docs

### PR DESCRIPTION
**Pull request by jkanner**
Working on improving the docs based on discussion with working group

### CODE REVIEW

**Comment by jkanner** [comment]
@kentblackburn Can you review these changes to the schema docs?

**Comment by DrKentB** [comment]
I really like the Overview!

In the Event List View section, I think it would be good to point out that the "catalog_description" is also displayed there (in the top card). Also the Event List View only shows specific key word/values in the table and it would be good to list those (I don't have the code in front of me, but that is probably the best place to dig them up). NOTE: If these are documented in the "Recognized parameters" section below, then just referring to that here would be fine.

In the Event Details View section, again I think referencing the Notes: below where it spells out that other values for the names are allowed and will be displayed would be useful (I'm thinking something simple like "see Notes below for details"). Also, in this section I think the use of 'often' in "and often points to a posterior sample file would serve everyone better if it was 'usually'.

In the 2. Events level section, for "detectors:" I think the statement: "is not needed for groups outside the LVK" should be "is not necessary for groups outside the LVK" ... subtle difference by I believe slightly more accurate. 

in the 4. PE sets level section, I think for the "is_preferred" there is another subtle aspect to capture here, to be properly desplayed in the catalog table, it must also be one of the recognized parameter names I was pointing out above.

In the Units section the acceptance of astropy units is limited to time, distance and mass. Units of (1 over time) in the far are converted to ifar (time) and modified to years and then converted back to (1 over years). Units of distance are converted from astropy units to Mpc and units of mass are converted to M_sun. Here is a tiny interpreted python script showing all the allowed astropy units we recognize with results (FOR COMPLETENESS IN THIS COMMENT - not necessarily for the doc unless you think this has value:

```
>>> import astropy.units as u
>>> equivTime = u.second.find_equivalent_units()
>>> equivDistance = u.pc.find_equivalent_units()
>>> equivMass = u.Msun.find_equivalent_units()
>>> print(equivTime)
  Primary name | Unit definition | Aliases 
[
  a            | 3.15576e+07 s   | annum    ,
  d            | 86400 s         | day      ,
  fortnight    | 1.2096e+06 s    |          ,
  h            | 3600 s          | hour, hr ,
  min          | 60 s            | minute   ,
  s            | irreducible     | second   ,
  sday         | 86164.1 s       |          ,
  wk           | 604800 s        | week     ,
  yr           | 3.15576e+07 s   | year     ,
]
>>> print(equivDistance)
  Primary name | Unit definition | Aliases                         
[
  AU           | 1.49598e+11 m   | au, astronomical_unit            ,
  Angstrom     | 1e-10 m         | AA, angstrom                     ,
  cm           | 0.01 m          | centimeter                       ,
  earthRad     | 6.3781e+06 m    | R_earth, Rearth                  ,
  jupiterRad   | 7.1492e+07 m    | R_jup, Rjup, R_jupiter, Rjupiter ,
  lsec         | 2.99792e+08 m   | lightsecond                      ,
  lyr          | 9.46073e+15 m   | lightyear                        ,
  m            | irreducible     | meter                            ,
  micron       | 1e-06 m         |                                  ,
  pc           | 3.08568e+16 m   | parsec                           ,
  solRad       | 6.957e+08 m     | R_sun, Rsun                      ,
]
>>> print(equivMass)
  Primary name | Unit definition | Aliases                         
[
  M_e          | 9.10938e-31 kg  |                                  ,
  M_p          | 1.67262e-27 kg  |                                  ,
  earthMass    | 5.97217e+24 kg  | M_earth, Mearth                  ,
  g            | 0.001 kg        | gram                             ,
  jupiterMass  | 1.89812e+27 kg  | M_jup, Mjup, M_jupiter, Mjupiter ,
  kg           | irreducible     | kilogram                         ,
  solMass      | 1.98841e+30 kg  | M_sun, Msun                      ,
  t            | 1000 kg         | tonne                            ,
  u            | 1.66054e-27 kg  | Da, Dalton                       ,
]
>>> exit()
```


FINALLY - This is a huge improvement! Thank you for digging into this.

**Comment by DrKentB** [comment]
Addition note on documentation: In the 'Notes' section I think the statement, "Other values for name are permitted and will be displayed on the Event Detail page" should be "Other values for name _with the exceptions of p_astro and network_matched_filter_snr, which are reserve keywords_, are permitted and will be displayed on the Event Detail page"

**Comment by jkanner** [comment]
Thanks, @DrKentB   These are helpful comments.  I will try to make these changes tomorrow.

**Comment by martinberoiz** [comment]
I found a few issues, I'll be posting them as soon as I can.

**Comment by martinberoiz** [comment]
I thought there were markdown formatting issues, but turns out I was wrong (I assumed breaking lines inside lists needed extra tab space and turns out you don't!).

My only suggestion is to add what's below, just to be super clear (it's just a suggestion if you think it's worth it).

- Keys marked "optional" are not required to be inlcuded. => Keys marked "optional" are not required to be inlcuded. All other keys are mandatory.

All the rest is good, thank you for taking the time to write this.

Also I should note: after we merge this the validation script may (is it?) be out of phase again. I want to update it, but I'm spread thin already. If I find time in this sprint, I'll add the updates, otherwise we should put time for this in next sprint.

**Comment by martinberoiz** [comment]
This closes #73 and #57.

**Comment by DrKentB** [comment]
@jkanner - doesn't look like this comment made it into the latest draft: 

Addition note on documentation: In the 'Notes' section I think the statement, "Other values for name are permitted and will be displayed on the Event Detail page" should be "Other values for name with the exceptions of p_astro and network_matched_filter_snr, which are reserve keywords, are permitted and will be displayed on the Event Detail page"

**Comment by jkanner** [comment]
@DrKentB @martinberoiz   Those notes are helpful - thanks!  I've made these additions.

**Comment by jkanner** [comment]
If this looks OK, we should go ahead and merge it soon and share the updates with Javier and Collin.

**Comment by martinberoiz** [comment]
looks good to me

**Comment by DrKentB** [comment]
yes, looks good to me as well!

**Pull request merged**
