### PR TITLE
Schema

### PR DESCRIPTION
**Pull request by jroulet**
This implements Python classes to instantiate a `Catalog` object, plus updates to the schema.

### CODE REVIEW

**Comment by martinberoiz** [comment]
In the README there are still references to `name`, `description`, etc instead of `catalog_name`, `catalog_description`.
Missing `release_date` in the README as well and same with the other changes.

If you don't have time and want me to complete it I can do it too.

**Comment by martinberoiz** [comment]
IIUC this will fix #5, #9, #13, #14, #17 is that right?

**Comment by jroulet** [comment]
Yes, this fixes #5, #9, #13, #14, #17 but also #15 and #16 (#15 in the sense that it allows one to include network SNR or any other search statistic, although it doesn't enforce it).

If you could update the README it would be great, thanks!

**Comment by martinberoiz** [comment]
Ok, great. I'll merge and continue from here.

**Review by martinberoiz — APPROVED** [review]

**Comment by martinberoiz** [comment]
Oh, I think I should have let _you_ merge? Anyway, damage is done now, sorry :(

**Pull request merged**
